# Replace the placeholder before applying the manifest:
# - <RA-CERT-PASSWORD> replace with the RA certificate password
apiVersion: cp.iot.sap/v1alpha1
kind: IoTService
metadata:
  name: example-iotservice # the instance_id
  namespace: devawsk8s
spec:
  instance_owner_pwd: Abcdefg12345
  client_auth_cert:
  - |-
    -----BEGIN CERTIFICATE-----
    MIID3DCCAsSgAwIBAgIBADANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJERTEj
    MCEGA1UEChMaU0FQIElvVCBUcnVzdCBDb21tdW5pdHkgSUkxIjAgBgNVBAMTGVNB
    UCBJbnRlcm5ldCBvZiBUaGluZ3MgQ0EwHhcNMTAxMDE4MTAwMDAwWhcNNDAwNzE4
    MTAwMDAwWjBWMQswCQYDVQQGEwJERTEjMCEGA1UEChMaU0FQIElvVCBUcnVzdCBD
    b21tdW5pdHkgSUkxIjAgBgNVBAMTGVNBUCBJbnRlcm5ldCBvZiBUaGluZ3MgQ0Ew
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD+d7h13CkCLVb8DAXR5Vlc
    1QAIpgs+BpfxD1VivRmGjMn8qfiy61sVZFDgWEPJs0/cgd4Xe2E+8xJQ8R/QtS0x
    uUHJietcNbYlJuZbx0IINbCwdKoqgeaUIkrydD40oEzv1df39kE3mAGERGS5wzMa
    6xiWnRWzF0/6d2S6g618WnYvmUaI5wB2podCaoUdoKkQvzmkMJkhMxxErxCP7Bx1
    hbv9C4GRVHjcStB6S5S74QxZfnYH/hdyQLf9NhgMR+04MLw3Y0PDJUt61j0QolDq
    OC/wI8pp0eqwSAKVXM+crryYtFqA4LsXGpPSadJjSAfoaLpgc3DLIc9ddJb22xAD
    AgMBAAGjgbQwgbEwSAYDVR0fBEEwPzA9oDugOYY3aHR0cHM6Ly90Y3MubXlzYXAu
    Y29tL2NybC9UcnVzdENvbW11bml0eUlJL1NBUElvVENBLmNybDAPBgNVHRMBAf8E
    BTADAQH/MCUGA1UdEQQeMByGGmh0dHA6Ly9zZXJ2aWNlLnNhcC5jb20vVENTMA4G
    A1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQUlbez9Vje1bSzWEbg8qbJeE69LXUwDQYJ
    KoZIhvcNAQELBQADggEBABQGiE4JlnH+WZT7PESMdlIl46jis85Z4i8AbVENs6RT
    8oVX1Wyh3GztpF41Iq4xM6G/lxidxjsdhj9y4rafnZkqbfcv7PSo7AojC5XmKmKG
    ma/mYpsbXZAgb3FWznYI5oqxlP2OfjY1xhlbvy0fhixR3qkSNDzujGEhXTOft3WN
    LqecYBkNXV3o1FTP79Co4AyilvFDQhh+I5afFHAwJlUewXdsOCX1/Hz+wgfAsf/o
    9IyAzG5ym8EZAeHxVJKGGcAqQBIXKOhFxs0JZP3EmgAAlLUwgrF5iRhUenC6qUsw
    P1pyzBSI+kS7WaGjmWyT8oI4ubflNZIfrqgWgPfg6ak=
    -----END CERTIFICATE-----
  - |-
    -----BEGIN CERTIFICATE-----
    MIIGBDCCA+ygAwIBAgIJAKi1aEV58cQ1MA0GCSqGSIb3DQEBCwUAMIGOMQswCQYD
    VQQGEwJERTEbMBkGA1UECAwSQmFkZW4tV3VlcnR0ZW1iZXJnMREwDwYDVQQHDAhX
    YWxsZG9yZjEPMA0GA1UECgwGU0FQIFNFMR8wHQYDVQQLDBZTQVAgQ1AgRGF0YSBN
    YW5hZ2VtZW50MR0wGwYDVQQDDBRTQVAgQ1AgS2Fma2EgUm9vdCBDQTAeFw0xNzEy
    MDQxMzUxMjZaFw0yMTAzMTgxMzUxMjZaMIGOMQswCQYDVQQGEwJERTEbMBkGA1UE
    CAwSQmFkZW4tV3VlcnR0ZW1iZXJnMREwDwYDVQQHDAhXYWxsZG9yZjEPMA0GA1UE
    CgwGU0FQIFNFMR8wHQYDVQQLDBZTQVAgQ1AgRGF0YSBNYW5hZ2VtZW50MR0wGwYD
    VQQDDBRTQVAgQ1AgS2Fma2EgUm9vdCBDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIP
    ADCCAgoCggIBAKCx+et7E53Znvy+bFB/y4IDjubIEZOg+nmCYmID2RV/6PGtHXLY
    DEwSue+JDwGXp4sLziFFHhoSjPx6OKLvwd1ww//FraDiGbeJY0BsnkpWVRbQiNyK
    fxDY+YCLhYTujdtPZqcPcCII4QnQk1PoOrmgHuONGqgjIVTuSOeGx6eIUh8JC3TW
    Z7EY0qKbnxCsVmyZudsO5Sh8AcDXNHAHJImoJ3uhWwU5YheCv24Jn0UcD/X843Jo
    J6PhhoCmrLTZCVYeirv9jQqTiks0IhjQEAL6m2W6UCJArePzyjY+HOaY20Umo8Lf
    CVjR0SfZric9g2+2XHkBex/73AMJbvyCvwER8oHwO9iGNeuHbkDdaicotQ5D7Nap
    uXLgPFm3y/CkqiBXoiqCJxy+duM3itmLeW/PbEtNMnbS0mG64tZHd9THFAh3I+ug
    w1+cQWzYO24EcdPQzaX8CpVJ8Au7aYc9QyyaayfTr4YxGYtMO0zay9tchEyChhtK
    koHmyISz1kxuudItoRDNnRdbfUX1QeKnYWsUtfeK5MED2dpUPO+IVp7qomdy+F4T
    KdQDvOlKBRFsngmyBbGeGB5wjXwTjuLfC0j6VIlfW0yMKhuePbqSPbVjGTFVefRo
    rgODPaIre72GtXjcaVISlqagFQgOurRE5Z9OLpgCrMsLdOqVJ9LnSNTrAgMBAAGj
    YzBhMB0GA1UdDgQWBBRkTG0qgjz9anjV94RGJ+GAApaf3DAfBgNVHSMEGDAWgBRk
    TG0qgjz9anjV94RGJ+GAApaf3DAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQE
    AwIBhjANBgkqhkiG9w0BAQsFAAOCAgEAjL3wUM+Kgzbii2F76/qK2C1asFJkVQRd
    CMiOhlZDEJYaBPzucF2vhOygkMMuw4SojkbzWGEdaRrc4IR6wVe0CezVeBrVRtAQ
    DmCzdxO0xEZkWNMmMnzPBiB6k4l5Y9WiOGWiCrzLcMi8fiXr4pJoaUirUsvGf7xf
    rwR6preFeLIZAgUesxy1RV2p9JHYm+iHiQskovkGt5Xr2sKJ+za3vtQ7Tf52rqAI
    LPdhZXrMsqcza7yVfiJtS0orn3Su489bj6j+/MKjYjS6DvrSnw1VfzW1eA0U9nYt
    vP8PVeWGsNxyg3YSwTaPi9cZ5lhGCoUSf2pq1g+VLvR1bIV++UL9wUHl4D7m5V4f
    jqve5XlMMxYPk9l0YcA4nMF4CxpPsFqzx2MYfbWb1/RiR1BaHqgx7dFWJt980vHp
    wM4tudQei+uUPYjLte09jKGLpZot0DGLIVJhT4RXnDV1VFmalRjJhJKBBIj7JPba
    NKWCBaob148p5gwZ4dr4N/yaaUhesdYPJjZn+uvO29/pvv+u80nkEEWW2KYOCd44
    SMTAhWkj5lx3X8xj40GSCxCMP+Jq2VLasoJSNminWVJuUaTk3veHsQ1mkoRDAbr1
    2wk9rLRZaQnhspt6MhlmU0qkaEZpYND3emR2XZ07m51jXqDUgTjXYCSggImUsARs
    NAehp9bMeco=
    -----END CERTIFICATE-----
  server_cert: |
    -----BEGIN CERTIFICATE-----
    MIIDJTCCAo6gAwIBAgIPALis1wxkbYqIEAEECBj/MA0GCSqGSIb3DQEBBQUAMEUx
    CzAJBgNVBAYTAkRFMRwwGgYDVQQKExNTQVAgVHJ1c3QgQ29tbXVuaXR5MRgwFgYD
    VQQDEw9TQVAgUGFzc3BvcnQgQ0EwHhcNMTYxMDI0MTAxNjU3WhcNMTcxMDI0MTAx
    NjU3WjBPMQswCQYDVQQGEwJERTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0
    eTEUMBIGA1UECxMLU0FQIFBPQyBJT1QxDDAKBgNVBAMTAzEyMzCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBAJNGGQ+QYOHqotJvzpuaX0xfABI5muzNJ7IE
    /N8YJB19gjCa3YLkSgOKifcNtJDwxXur2cxM4h2KaEo1fcm46MTUnUH0c8vxAkH0
    JgFpSGbN4em34JXLUNSbfOwqAf38uwuvYL1VjTWJPc845gBNaZP+wEv75iA06Pyu
    T4dmwPhDepsXI5YWOl9e6eu2Id1rsqZtUcN7hhkA8sRCxqTwb6qrtN0Pa1CObGE1
    ALuFBAOnPlqI74C+aOqf2zA0F+T8Yrzx5nqrs3PrTnhwSyjF3KISPrujGM4Sb/0R
    wz1Amfc0a30FgMht/xqShEI/6fxA1mqgYODgD8Z88TMy5hgbLlMCAwEAAaOBiDCB
    hTAMBgNVHRMBAf8EAjAAMCUGA1UdEgQeMByGGmh0dHA6Ly9zZXJ2aWNlLnNhcC5j
    b20vVENTMA4GA1UdDwEB/wQEAwIE8DAdBgNVHQ4EFgQUsmGFd1gnUV2tqP1wEap6
    0sBI8d0wHwYDVR0jBBgwFoAUGkRFpldxcFYBHHgkelE2TMA10F4wDQYJKoZIhvcN
    AQEFBQADgYEAyRH4csBSQ/8r/NQYSYCuTBK4lT9+uDGRtAQvOOguZtYx4WdXKuiE
    PfYfMC4VNISL5h/oxt4wWOvUzbIvoJJB9DHsIHm737mjCFElY9G/6VlJ7PvJApAZ
    lrJ44CHM9t7Oz+X+AVhxacRWjl5F8/PB3IzsHdlWOk1wTwpiIywuqlQ=
    -----END CERTIFICATE-----
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCTRhkPkGDh6qLS
    b86bml9MXwASOZrszSeyBPzfGCQdfYIwmt2C5EoDion3DbSQ8MV7q9nMTOIdimhK
    NX3JuOjE1J1B9HPL8QJB9CYBaUhmzeHpt+CVy1DUm3zsKgH9/LsLr2C9VY01iT3P
    OOYATWmT/sBL++YgNOj8rk+HZsD4Q3qbFyOWFjpfXunrtiHda7KmbVHDe4YZAPLE
    Qsak8G+qq7TdD2tQjmxhNQC7hQQDpz5aiO+Avmjqn9swNBfk/GK88eZ6q7Nz6054
    cEsoxdyiEj67oxjOEm/9EcM9QJn3NGt9BYDIbf8akoRCP+n8QNZqoGDg4A/GfPEz
    MuYYGy5TAgMBAAECggEAFhZsScZIkXlkRBVaskGby1NwKkuTbbJzIqLW3gq71+Rr
    8yg20pu0cgWEHZZjn11M8PhcKOTbAL0yWPbez7M4zdRpZWvpNgwGX6fjT1Df9/Mm
    z6uxNiYREGHlgXHnbJVL5DvAUYUUMZRMvdh1vlPd4sFRS9QStn/Y9ZSa/t6tUE5q
    HKHFkfAb3kWqe/QAVAb3XMqGVBqh6xH5/xIQxPs/+XyEW8eL3d8lbdYF74qLh16R
    z9ibRR6UorgBh2OJEO3FRhP4CdVrHttGHb7XAH3P/ht19OKTuISvepZipZWTELqr
    dBGLrqVN4d/07zffhNaVxFda1TWnnX2zB0yOLM7jWQKBgQD+wVrGM3UJWnEaZmTr
    mv9nB+9JnBUwfrt7a7aS9jB1JlSZ/ig24ZFxSreqQJRnEM1tinnU1XcmCe6djoGR
    B7XxQX1V/fwofur5RGiaYOqXOi/jDTb7H2ROXmKgkrj5U1mNVgdNDm4nXoxX9dNN
    O7DI4wxAUcBrtsrbzv9GZOj9RwKBgQCT/k55XZXQkDSpD8mwxrMnmsv7iBTJJcyW
    frPY3HWEGHKPkoO4f67WO+5aygBKYxPrDj6U9ZBMgbbVhJpe82RWjiZLhieCTYTu
    OCV3jOUGiMszvqkmiQi3m6qY8GCy49RMshnyZleMvsNYd4jM3ZMVmwgGSmc31sc+
    sw1FztQclQKBgQCv0mTC7Bq3VNtAnDDExtnEkx5cEEQzjxP373Q3Y4A4KjczfMzm
    a7HEngu6jg2eQGN3WZ4R/S3Za/tqdEMKBGdW1ZsaMUvJ6yZi2QrUmVTvAHKyYply
    oczJpayuI/VT5mmk+R3a2b2+oCt+PaQS5sJxMvpunb2O2b6SC//05opC2wKBgQCH
    IYEEHqjKHLKI4EqYqIYzlovFK7dXB7WsgRq03HBNYolQgUbW83dwVJ7KtYHYamlo
    isQn/aV5xkNs6TyPkIxA4GElOuTefOvxHMFRTQxekA+DOwd2kU+tX21BYtPY5GEY
    etNoW3x7nj/+in8WGQfRhZKpM8zV1r5tiM6IvFc/lQKBgFr2sjQOeePbyezoWsj/
    uzHNPPXyhTyDnzDiRTCi5TIDiLvgBQOwdCZ/kzkpX5YjDzH/yrNuerCBRh4KMR6F
    CBINkGxpUbyUCh2MweH6p+3m4ueGJHmlJYs1nFXfXW5iFByB4lJZNSkmsgouquT1
    3UugQK6PHve81lXYP36RWVZL
    -----END PRIVATE KEY-----
    -----BEGIN CERTIFICATE-----
    MIICjzCCAfigAwIBAgIEAQAAATANBgkqhkiG9w0BAQUFADBFMQswCQYDVQQGEwJE
    RTEcMBoGA1UEChMTU0FQIFRydXN0IENvbW11bml0eTEYMBYGA1UEAxMPU0FQIFBh
    c3Nwb3J0IENBMB4XDTAwMDcxODEwMDAwMFoXDTE4MDQwMTEwMDAwMFowRTELMAkG
    A1UEBhMCREUxHDAaBgNVBAoTE1NBUCBUcnVzdCBDb21tdW5pdHkxGDAWBgNVBAMT
    D1NBUCBQYXNzcG9ydCBDQTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA/2rT
    TxBHa450XQCJ/ENotmAwKpFdyKWdU7KC4p8X0VEz/DB4Zu5Digq91f9wxsAYyvbh
    hvoZ5nZimr1sFiWw60gCryDI2qINowZX/sWmYGqguVyBrTxjjEwnAYQXno53RFR5
    p0Aa9RLfLNSITWeHeELKT5ahpGckGdrh4R6+vSMCAwEAAaOBizCBiDAPBgNVHRMB
    Af8EBTADAQH/MCUGA1UdEQQeMByGGmh0dHA6Ly9zZXJ2aWNlLnNhcC5jb20vVENT
    MA4GA1UdDwEB/wQEAwIB9jAdBgNVHQ4EFgQUGkRFpldxcFYBHHgkelE2TMA10F4w
    HwYDVR0jBBgwFoAUGkRFpldxcFYBHHgkelE2TMA10F4wDQYJKoZIhvcNAQEFBQAD
    gYEAv0uSi6v5UX9KYhzhV8ZNjKL+QBfSmaom/S7I0e0fga0pIkTpwjGsUcnaCf3X
    JiNZnDUDCrl91KUdpJujSwOhr69PxHUeP11q/rQWd7h2ZpzSS6Hmug/fzQzXWAzy
    hl+hNrh2liQOSaPooV4WZA7o1+HhDyvZP54op19p245ZZC0=
    -----END CERTIFICATE-----
  domain_name: example-iotservice.devaws.cp.iot.sap
  mms:
    image: iot-service-dev.docker.repositories.sap.ondemand.com/messaging:4.33.0
    size: 1
    listening_address: 0.0.0.0
    max_heap_size: 1g
    amq_store_size_mb: 5000
    resources:
      requests:
        memory: 1000Mi
      #  cpu: 300m
      limits:
        memory: 1500Mi
      #  cpu: 1000m
  core:
    image: iot-service-dev.docker.repositories.sap.ondemand.com/core:4.33.0
    size: 1
    listening_address: 0.0.0.0
    max_heap_size: 3g
    resources:
      requests:
        memory: 2500Mi
      #  cpu: 300m
      limits:
        memory: 4000Mi
      #  cpu: 1000m
  core_spring:
    image: iot-service-dev.docker.repositories.sap.ondemand.com/core-spring:4.33.0
    size: 1
    resources:
      requests:
        memory: 1000Mi
      #  cpu: 300m
      limits:
        memory: 1500Mi
      #  cpu: 1000m
    enabled: true
    max_heap_size: 1g
    database:
      hostname: postgresql-example-iotservice.iot-example-iotservice.svc.cluster.local
      port: '5432'
      dbadminuser: iotuser
      dbadminpassword: I0TdbAcce55
  data_migration:
    enabled: false
  processing:
    image: iot-service-dev.docker.repositories.sap.ondemand.com/processing:4.33.0
    size: 1
    resources:
      requests:
        memory: 1500Mi
      #  cpu: 300m
      limits:
        memory: 2500Mi
      #  cpu: 1000m
    max_heap_size: 2g
    database:
      hostname: postgresql-example-iotservice.iot-example-iotservice.svc.cluster.local
      port: '5432'
      dbadminuser: iotuser
      dbadminpassword: I0TdbAcce55
    types:
      kafka:
        enabled: true
      iotae:
        enabled: true
        user: kafka_user
        password: kafka_password
        brokers: 10.254.20.21:9093,10.254.20.22:9093,10.254.20.23:9093,10.254.20.24:9093,10.254.20.25:9093
        token_url: https://kafka-service-oauth.cf.eu10.hana.ondemand.com/v1/someid/token
        subaccount_id: '1234'
      sql:
        enabled: false
      internalsql:
        enabled: false
      http:
        enabled: false
  cockpit:
    image: iot-service-dev.docker.repositories.sap.ondemand.com/cockpit:4.33.0
    size: 1
    listening_address: 0.0.0.0
    max_heap_size: 1g
    iot_connect_365:
      enabled: false
      host: # some url string, possibly empty as here
      application_token: # some string, possibly empty as here
    resources:
      requests:
        memory: 400Mi
      #  cpu: 300m
      limits:
        memory: 1500Mi
      #  cpu: 1000m
  gateway:
    enable_device_vitality: true
    enable_measure_validation: true
    mqtt:
      image: iot-service-dev.docker.repositories.sap.ondemand.com/gateway-mqtt:4.33.0
      size: 1
      listening_address: 0.0.0.0
      max_heap_size: 1g
      amq_store_size_mb: 10000
      resources:
        requests:
          memory: 1300Mi
        #  cpu: 300m
        limits:
          memory: 1500Mi
        #  cpu: 1000m
    rest:
      image: iot-service-dev.docker.repositories.sap.ondemand.com/gateway-rest:4.33.0
      size: 1
      listening_address: 0.0.0.0
      max_heap_size: 1g
      resources:
        requests:
          memory: 1300Mi
        #  cpu: 300m
        limits:
          memory: 1500Mi
        #  cpu: 1000m
  haproxy:
    image: iot-service-dev.docker.repositories.sap.ondemand.com/haproxy:4.33.0
    size: 1
    resources:
      requests:
        memory: 50Mi
      #  cpu: 200m
      limits:
        memory: 100Mi
      #  cpu: 500m
  postgresql:
    image: iot-service-dev.docker.repositories.sap.ondemand.com/postgresql:latest
    size: 1
    resources:
      requests:
        memory: 500Mi
      #  cpu: 1000m
      limits:
        memory: 500Mi
      #  cpu: 1500m
  certificate:
    provider: tcs
    registration_authority_certificate_password: <RA-CERT-PASSWORD> # replace with the RA certificate password
    tcs:
      certificate_authority_url:  https://tcs.mysap.com/invoke/tc/usercert
  metering:
    maas:
      enabled: false
      organization_id: sap
      space_id: dev
      instance_id: example-iotservice
      domain: #some string, possibly empty as here
      region: #some string, possibly empty as here
      client_id: #some string, possibly empty as here
      client_secret: #some string, possibly empty as here
    enabled: false
    organization_id: sap
    space_id: dev
    domain: #some string, possibly empty as here
    instance_id: example-iotservice
    resource_id: #some string, possibly empty as here
    user: #some string, possibly empty as here
    password: #some string, possibly empty as here
  processing_services:
  - name: sql
  - name: kafka
    properties:
      processing.kafka.brokers: 10.254.20.21:9093,10.254.20.22:9093,10.254.20.23:9093,10.254.20.24:9093,10.254.20.25:9093
      processing.kafka.topic.metadata: sometopic.sap.v1.iot.metadata
      processing.kafka.topic.measures: sometopic.sap.v1.iot.raw_timeseries
      processing.kafka.user: kafka_user
      processing.kafka.password: kafka_password
      processing.kafka.tokenurl: https://kafka-service-oauth.cf.eu10.hana.ondemand.com/v1/someid/token
  packetdb:
    hostname: postgresql-example-iotservice.iot-example-iotservice.svc.cluster.local
    port: '5432'
    dbadminuser: iotuser
    dbadminpassword: I0TdbAcce55
  last_alive:
    enabled: false
    period_seconds: #some number, possibly empty as here
  enable_multi_protocol_support: false
  jwt_validation_url: #some url string, possibly empty as here
  imagePullPolicy: Always # can be changed to 'IfNotPresent' later, when development stabilizes
  imagePullSecrets: image-pull-secret
  enableNetworkPolicies: true
