apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iotservices.cp.iot.sap
spec:
  group: cp.iot.sap
  versions:
    - name: v1alpha1
      served: true
      storage: false
    - name: v1
      served: true
      storage: true
  conversion:
    strategy: None
  names:
    kind: IoTService
    listKind: IoTServiceList
    plural: iotservices
    singular: iotservice
    shortNames:
      - iot
  scope: Namespaced
  additionalPrinterColumns:
    - name: Status
      type: string
      description: The status of the service instance
      JSONPath: .status.phase
  subresources:
    status: {}
