// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppConfig) DeepCopyInto(out *AppConfig) {
	*out = *in
	in.IoTServices.DeepCopyInto(&out.IoTServices)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConfig.
func (in *AppConfig) DeepCopy() *AppConfig {
	if in == nil {
		return nil
	}
	out := new(AppConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLog) DeepCopyInto(out *AuditLog) {
	*out = *in
	out.AuditLogLastEventCache = in.AuditLogLastEventCache
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLog.
func (in *AuditLog) DeepCopy() *AuditLog {
	if in == nil {
		return nil
	}
	out := new(AuditLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogLastEventCache) DeepCopyInto(out *AuditLogLastEventCache) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogLastEventCache.
func (in *AuditLogLastEventCache) DeepCopy() *AuditLogLastEventCache {
	if in == nil {
		return nil
	}
	out := new(AuditLogLastEventCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cockpit) DeepCopyInto(out *Cockpit) {
	*out = *in
	out.Cockpit = in.Cockpit
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cockpit.
func (in *Cockpit) DeepCopy() *Cockpit {
	if in == nil {
		return nil
	}
	out := new(Cockpit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Core) DeepCopyInto(out *Core) {
	*out = *in
	out.Core = in.Core
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Core.
func (in *Core) DeepCopy() *Core {
	if in == nil {
		return nil
	}
	out := new(Core)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreSpring) DeepCopyInto(out *CoreSpring) {
	*out = *in
	out.CoreSpring = in.CoreSpring
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreSpring.
func (in *CoreSpring) DeepCopy() *CoreSpring {
	if in == nil {
		return nil
	}
	out := new(CoreSpring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gateway) DeepCopyInto(out *Gateway) {
	*out = *in
	out.Mqtt = in.Mqtt
	out.Rest = in.Rest
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gateway.
func (in *Gateway) DeepCopy() *Gateway {
	if in == nil {
		return nil
	}
	out := new(Gateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Haproxy) DeepCopyInto(out *Haproxy) {
	*out = *in
	out.Haproxy = in.Haproxy
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Haproxy.
func (in *Haproxy) DeepCopy() *Haproxy {
	if in == nil {
		return nil
	}
	out := new(Haproxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoTService) DeepCopyInto(out *IoTService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoTService.
func (in *IoTService) DeepCopy() *IoTService {
	if in == nil {
		return nil
	}
	out := new(IoTService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IoTService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoTServiceList) DeepCopyInto(out *IoTServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IoTService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoTServiceList.
func (in *IoTServiceList) DeepCopy() *IoTServiceList {
	if in == nil {
		return nil
	}
	out := new(IoTServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IoTServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoTServiceSpec) DeepCopyInto(out *IoTServiceSpec) {
	*out = *in
	if in.ClientAuthCert != nil {
		in, out := &in.ClientAuthCert, &out.ClientAuthCert
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Mms = in.Mms
	out.Core = in.Core
	out.CoreSpring = in.CoreSpring
	out.DataMigration = in.DataMigration
	out.MeasureMigration = in.MeasureMigration
	out.ProcessingService = in.ProcessingService
	out.Cockpit = in.Cockpit
	out.Gateway = in.Gateway
	out.Haproxy = in.Haproxy
	out.Postgresql = in.Postgresql
	out.Certificate = in.Certificate
	out.Metering = in.Metering
	out.Packetdb = in.Packetdb
	out.LastAlive = in.LastAlive
	out.AuditLog = in.AuditLog
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoTServiceSpec.
func (in *IoTServiceSpec) DeepCopy() *IoTServiceSpec {
	if in == nil {
		return nil
	}
	out := new(IoTServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeasureMigration) DeepCopyInto(out *MeasureMigration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeasureMigration.
func (in *MeasureMigration) DeepCopy() *MeasureMigration {
	if in == nil {
		return nil
	}
	out := new(MeasureMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mms) DeepCopyInto(out *Mms) {
	*out = *in
	out.Mms = in.Mms
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mms.
func (in *Mms) DeepCopy() *Mms {
	if in == nil {
		return nil
	}
	out := new(Mms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mqtt) DeepCopyInto(out *Mqtt) {
	*out = *in
	out.Mqtt = in.Mqtt
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mqtt.
func (in *Mqtt) DeepCopy() *Mqtt {
	if in == nil {
		return nil
	}
	out := new(Mqtt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Postgresql) DeepCopyInto(out *Postgresql) {
	*out = *in
	out.Postgresql = in.Postgresql
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Postgresql.
func (in *Postgresql) DeepCopy() *Postgresql {
	if in == nil {
		return nil
	}
	out := new(Postgresql)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessingService) DeepCopyInto(out *ProcessingService) {
	*out = *in
	out.ProcessingService = in.ProcessingService
	out.KafkaProducer = in.KafkaProducer
	out.ThroughputConfiguration = in.ThroughputConfiguration
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessingService.
func (in *ProcessingService) DeepCopy() *ProcessingService {
	if in == nil {
		return nil
	}
	out := new(ProcessingService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rest) DeepCopyInto(out *Rest) {
	*out = *in
	out.Rest = in.Rest
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rest.
func (in *Rest) DeepCopy() *Rest {
	if in == nil {
		return nil
	}
	out := new(Rest)
	in.DeepCopyInto(out)
	return out
}
